.TH "Music Player Daemon" 1
.SH NAME
MPD \- A daemon for playing music
.SH SYNOPSIS
.B mpd
.RI [ options ]
.RI [ CONF_FILE ]
.SH DESCRIPTION
MPD is a daemon for playing music.  Music is played through the configured
audio output(s) (which are generally local, but can be remote).  The daemon
stores info about all available music, and this info can be easily searched and
retrieved.  Player control, info retrieval, and playlist management can all be
managed remotely.

MPD searches for a config file in \fB~/.mpdconf\fP then \fB/etc/mpd.conf\fP or
uses CONF_FILE.

Read more about MPD at <\fBhttp://www.musicpd.org/\fP>.
.SH OPTIONS
.TP
.BI --help
Output a brief help message.
.TP
.BI --kill
Kill the currently running mpd session.  The pid_file parameter must be
specified in the config file for this to work.
.TP
.BI --create-db
Force (re)creation of database.
.TP
.BI --no-create-db
Do not create database, even if it doesn't exist.
.TP
.BI --no-daemon
Don't detach from console.
.TP
.BI --stdout
Print messages to stdout and stderr.
.TP
.BI --verbose
Verbose logging.
.TP
.BI --version
Print version information.
.SH FILES
.TP
.BI ~/.mpdconf
User configuration file.
.TP
.BI /etc/mpd.conf
Global configuration file.
.SH SEE ALSO
mpd.conf(5), mpc(1)
.SH BUGS
If you find a bug, please report it at
.br
<\fBhttp://www.musicpd.org/mantis/bug_report_page.php\fP>.
.SH AUTHORS
Warren Dukes <warren.dukes@gmail.com>

Special thanks to all the people that provided feedback and patches.
