#ifndef ACK_H
#define ACK_H

#define ACK_ERROR_NOT_LIST		1
#define ACK_ERROR_ARG			2
#define ACK_ERROR_PASSWORD		3
#define ACK_ERROR_PERMISSION		4
#define ACK_ERROR_UNKNOWN		5
#define ACK_ERROR_NO_EXIST		6
#define ACK_ERROR_PLAYLIST_MAX		7
#define ACK_ERROR_SYSTEM		8
#define ACK_ERROR_PLAYLIST_LOAD		9
#define ACK_ERROR_UPDATE_ALREADY	10
#define ACK_ERROR_PLAYER_SYNC		11

#endif
