---
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'AUTHORS'
      - 'COPYING'
      - 'LICENSES/**'
      - 'NEWS'
      - 'README.md'
      - 'android/**'
      - 'doc/**'
      - 'systemd/**'
    branches:
      - master
      - v0.24.x
  pull_request:
    paths-ignore:
      - 'AUTHORS'
      - 'COPYING'
      - 'LICENSES/**'
      - 'NEWS'
      - 'README.md'
      - 'android/**'
      - 'doc/**'
      - 'systemd/**'
    branches:
      - master
      - v0.24.x

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build-linux:
    strategy:
      matrix:
        cpu: [x86-64, i686]
        include:
          - cpu: x86-64
            packages: g++-mingw-w64-x86-64
            bits: 64
          - cpu: i686
            packages: g++-mingw-w64-i686
            bits: 32

    runs-on: ubuntu-24.04

    env:
      CC: ccache ${{matrix.cpu}}-w64-mingw32-g++
      CXX: ccache ${{matrix.cpu}}-w64-mingw32-gcc

    steps:
      - id: checkout
        uses: actions/checkout@v7

      - name: "Cache third-party library tarballs"
        uses: actions/cache@v6
        with:
          key: lib-tarballs-windows-${{hashFiles('win32/configure.py', 'python/**')}}
          path: |
            ${{github.workspace}}/output/lib/download

      - name: "Restore third-party libraries"
        id: cache-libs
        uses: actions/cache/restore@v6
        with:
          key: libs-mingw-${{matrix.cpu}}-${{hashFiles('win32/configure.py', 'python/**')}}-${{github.run_id}}
          restore-keys: |
            libs-mingw-${{matrix.cpu}}-${{hashFiles('win32/configure.py', 'python/**')}}-
          path: |
            ${{github.workspace}}/output/lib/*/root

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            ${{ matrix.packages }} \
            ccache \
            cmake \
            gperf \
            meson \
            nasm \
            pkg-config \
            quilt

      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: mingw-${{ matrix.cpu }}

      - name: Configure
        run: |
          mkdir -p output
          cd output
          ../win32/configure.py --${{matrix.bits}} \
            --buildtype=debug \
            --werror \
            -Dtest=true \
            -Ddocumentation=disabled \
            -Dupnp=disabled \
            -Dcurl=enabled \
            -Dffmpeg=enabled \
            -Did3tag=enabled \
            -Dlibmpdclient=enabled \
            -Dnfs=enabled \
            -Dsqlite=enabled \
            -Dwebdav=enabled \
            -Dzlib=enabled \
            -Dwrap_mode=forcefallback

      # If any library was built (i.e. a library build directory exists),
      # save the cache, even if the cache was restored successfully (which
      # would make actions/cache skip the save) and even if the build has
      # failed.
      - name: "Check for third-party library builds"
        id: check-libs
        if: always()
        run: |
          if ls -d output/lib/*/build >/dev/null 2>&1; then
            echo "built=true" >> $GITHUB_OUTPUT
          fi

      - name: "Save third-party libraries"
        if: always() && steps.check-libs.outputs.built == 'true'
        uses: actions/cache/save@v6
        with:
          key: ${{steps.cache-libs.outputs.cache-primary-key}}
          path: |
            ${{github.workspace}}/output/lib/*/root

      - name: Build
        run: meson compile -C output --verbose
