---
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'AUTHORS'
      - 'COPYING'
      - 'LICENSES/**'
      - 'NEWS'
      - 'README.md'
      - 'build/**'
      - 'doc/**'
      - 'subprojects/**'
      - 'systemd/**'
      - 'win32/**'
    branches:
      - master
      - v0.24.x
  pull_request:
    paths-ignore:
      - 'AUTHORS'
      - 'COPYING'
      - 'LICENSES/**'
      - 'NEWS'
      - 'README.md'
      - 'build/**'
      - 'doc/**'
      - 'subprojects/**'
      - 'systemd/**'
      - 'win32/**'
    branches:
      - master
      - v0.24.x

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
  build-android:
    strategy:
      matrix:
        abi: [arm64-v8a, x86_64]

    runs-on: ubuntu-24.04
    steps:
      - id: checkout
        uses: actions/checkout@v7

      - name: "Cache third-party library tarballs"
        uses: actions/cache@v6
        with:
          key: lib-tarballs-android-${{hashFiles('android/configure.py', 'python/**')}}
          path: |
            ${{github.workspace}}/output/lib/download

      - name: "Restore third-party libraries"
        id: cache-libs
        uses: actions/cache/restore@v6
        with:
          key: libs-android-${{matrix.abi}}-${{hashFiles('android/configure.py', 'python/**')}}-${{github.run_id}}
          restore-keys: |
            libs-android-${{matrix.abi}}-${{hashFiles('android/configure.py', 'python/**')}}-
          path: |
            ${{github.workspace}}/output/lib/*/root

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            meson \
            ccache \
            nasm \
            quilt 

      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: android-${{ matrix.abi }}

      - name: Configure
        run: |
          mkdir -p output
          cd ./output
          ../android/configure.py \
            $ANDROID_SDK_ROOT $ANDROID_NDK_LATEST_HOME \
            ${{matrix.abi}} \
            --buildtype=debugoptimized -Db_ndebug=true \
            -Dwrap_mode=forcefallback 

      # If any library was built (i.e. a library build directory exists),
      # save the cache, even if the cache was restored successfully (which
      # would make actions/cache skip the save) and even if the build has
      # failed.
      - name: "Check for third-party library builds"
        id: check-libs
        if: always()
        run: |
          if ls -d output/lib/*/build >/dev/null 2>&1; then
            echo "built=true" >> $GITHUB_OUTPUT
          fi

      - name: "Save third-party libraries"
        if: always() && steps.check-libs.outputs.built == 'true'
        uses: actions/cache/save@v6
        with:
          key: ${{steps.cache-libs.outputs.cache-primary-key}}
          path: |
            ${{github.workspace}}/output/lib/*/root


      - name: Build Native
        run: meson compile -C output --verbose

      - name: Install Native
        run: meson install -C output

      - name: Build Java
        run: |
          cd ./android
          export JAVA_HOME=$JAVA_HOME_17_X64
          ./gradlew assembleDebug
